#! /bin/sh

ARCH="x86_64-linux-gnu"

export PATH=$SNAP/nwjs:$PATH
export LD_LIBRARY_PATH="$SNAP/nwjs/lib:$SNAP/lib/$ARCH:$SNAP/usr/lib/$ARCH/dri:$SNAP/usr/lib/$ARCH:$SNAP/usr/lib/$ARCH/mesa:$SNAP/usr/lib/$ARCH/pulseaudio:$LD_LIBRARY_PATH"

export XDG_DATA_HOME="$SNAP/usr/share"

export FONTCONFIG_PATH="$SNAP/etc/fonts"
export FONTCONFIG_FILE="$SNAP/etc/fonts/fonts.conf"

export LIBGL_DRIVERS_PATH="$SNAP/usr/lib/$ARCH/dri"

#cd $SNAP_USER_DATA

exec nw "$@"
