name: nw
version: 0.15.4
summary: node-webkit, NW.js framework
description: the NW.js framework for node based webapps
confinement: devmode

apps:
  nw:
    command: bin/nw
    plugs: [opengl, home, x11, network, network-bind, pulseaudio]

parts:
  nwjs:
    source: "http://dl.nwjs.io/v0.15.4/nwjs-v0.15.4-linux-x64.tar.gz"
    plugin: copy
    files:
      "*": nwjs/
    stage-packages:
      - fontconfig-config
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libnss3
      - libpulse0
  fixperms:
    source: .
    plugin: make
    after: [nwjs]

