name: nw
version: 0.1
summary: node-webkit, NW.js framework
description: the NW.js framework for node based webapps
confinement: devmode

apps:
  nw:
    command: bin/nw
    plugs: [unity7, opengl, gsettings, home, x11, network, network-bind, pulseaudio]

parts:
  nwjs:
    source: "http://dl.nwjs.io/v0.15.4/nwjs-v0.15.4-linux-x64.tar.gz"
    plugin: copy
    files:
      credits.html: nwjs/credits.html
      icudtl.dat: nwjs/icudtl.dat
      lib: nwjs/
      locales: nwjs/locales
      natives_blob.bin: nwjs/natives_blob.bin
      nw: nwjs/nw
      nw_100_percent.pak: nwjs/nw_100_percent.pak
      nw_200_percent.pak: nwjs/nw_200_percent.pak
      nw_material_100_percent.pak: nwjs/nw_material_100_percent.pak
      nw_material_200_percent.pak: nwjs/nw_material_200_percent.pak
      resources.pak: nwjs/resources.pak
      snapshot_blob.bin: nwjs/snapshot_blob.bin
      ../../../nw: bin/nw
    stage-packages:
      - fontconfig-config
      - libgcrypt20
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglib2.0-0
      - libgtk-3-0
      - libnss3
      - libpulse0
      - libudev1
      - libxtst6
  fixperms:
    source: .
    plugin: make
    after: [nwjs]

